version: '3'
services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.11
    volumes:
      - .:/workspace
    command: sleep infinity
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_arm
      MYSQL_USER: arm
      MYSQL_PASSWORD: arm
    ports:
      - "3306:3306"